In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\suraj\testpalce 2\Bank_Customer_Churn_(U).csv")
data

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42.0,2,0.00,1,1,1.0,101348.88,1
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1.0,112542.58,0
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0.0,113931.57,1
3,15701354,699,France,Female,39.0,1,0.00,2,0,0.0,93826.63,0
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,France,Male,39.0,5,0.00,2,1,0.0,96270.64,0
9996,15569892,516,NaN,Male,35.0,10,57369.61,1,1,NaN,101699.77,0
9997,15584532,709,France,NaN,36.0,7,0.00,1,0,1.0,42085.58,1
9998,15682355,772,Germany,Male,42.0,3,75075.31,2,1,0.0,92888.52,1
9999,15628319,792,France,Female,28.0,4,130142.79,1,1,0.0,38190.78,0

In [4]:
#1

In [5]:
data['country'] = data['country'].fillna('India')

In [15]:
#2

In [8]:
# total count of gender without nan
print(data['gender'].value_counts(dropna=False))

gender
Male      4922
Female    4080
NaN        998
Name: count, dtype: int64

In [14]:
# male is graeter than female 
data['gender']=data['gender'].fillna('Male')

In [16]:
#3

In [17]:
mean_age = data['age'].mean()
data['age'] = data['age'].fillna(mean_age)
data['age'] = data['age'].astype(int)

In [18]:
#4

In [26]:
avg = round(data['balance'].mean(), 2)      
maxx = round(data['balance'].max(), 2) 

miss_index = data[data['balance'].isna()].index
data.loc[miss_index[:500], 'balance'] = avg
data.loc[miss_index[500:1000], 'balance'] = maxx
data.loc[miss_index[1000:], 'balance'] = 0.00

In [23]:
#5

In [21]:
data['active_member'].isnull().sum()

np.int64(1028)

In [22]:
1028/2

514.0

In [24]:
data['active_member']=data['active_member'].fillna(1.0,limit=514)
data['active_member']=data['active_member'].fillna(0.0,limit=514)

In [27]:
data

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1.0,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1.0,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0.0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0.0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,France,Male,39,5,0.00,2,1,0.0,96270.64,0
9996,15569892,516,India,Male,35,10,57369.61,1,1,0.0,101699.77,0
9997,15584532,709,France,Male,36,7,0.00,1,0,1.0,42085.58,1
9998,15682355,772,Germany,Male,42,3,75075.31,2,1,0.0,92888.52,1
9999,15628319,792,France,Female,28,4,130142.79,1,1,0.0,38190.78,0

In [28]:
#6

In [30]:
meanx=round(data['estimated_salary'].mean(),2)

In [32]:
data['estimated_salary']=data['estimated_salary'].fillna(meanx).round(2)

In [33]:
#7

In [34]:
data2 = data[['customer_id' ,'credit_score' ,'balance' ,'products_number' ,'credit_card' ,'active_member' ,'estimated_salary' ,'churn']]

In [42]:
data2.to_csv("Account_Fact.csv",index = False)

In [36]:
data3 = data[['customer_id', 'country', 'gender' ,'age' ,'tenure']]

In [41]:
data3.to_csv("Customer_Dim.csv",index = False)

In [43]:
data.to_csv("bank_clean.csv" , index = False)

In [40]:
pwd

'C:\\Users\\suraj\\testpalce 2'